export const FETCH_LIBRARY = 'FETCH_LIBRARY';
export const FETCH_LIBRARY_START = 'FETCH_LIBRARY_START';
export const FETCH_LIBRARY_SUCCESS = 'FETCH_LIBRARY_SUCCESS';
export const SET_PAGE = 'SET_PAGE';
export const CHANGE_CRITERION = 'CHANGE_CRITERION';
export const CHANGE_DIRECTION = 'CHANGE_DIRECTION';
export const MARK_WORDS_REVISED = 'MARK_WORDS_REVISED';
